const NAVBAR_HEIGHT = 70
const FOOTER_HEIGHT = 70
const SIDEBAR_COLLAPSE_WIDTH = 70
const SIDEBAR_EXPAND_WIDTH = 270

export { NAVBAR_HEIGHT, FOOTER_HEIGHT, SIDEBAR_COLLAPSE_WIDTH, SIDEBAR_EXPAND_WIDTH }
